dist: pursoul
language: python
python:
  - "3.7.0"
install:
  - sudo apt-get install ruby-coveralls
  - pip install --trusted-host pypi.python.org  -r requirements.txt

script:
  - ./init.sh

after_success:
  - coveralls
